-- INDEX 만들 때 새로운 테이블 생성 후 진행

SELECT * FROM TB_STUDENT;
DESC TB_STUDENT;
-- 우선 PRIMARY KEY 없이 순수한 테이블 생성
CREATE TABLE IDX_TEST(
     STUDENT_NO   VARCHAR2(10)
    ,STUDENT_NAME VARCHAR2(50) NOT NULL	
    ,STUDENT_SSN VARCHAR2(14)
    ,STUDENT_ADDRESS VARCHAR2(100)
);
-- 추가해주기
INSERT INTO IDX_TEST(
    SELECT STUDENT_NO
          ,STUDENT_NAME
          ,STUDENT_SSN
          ,STUDENT_ADDRESS
    FROM TB_STUDENT
);
-- 저장 여부 확인
SELECT * FROM IDX_TEST;

--ROWID 조회하기
SELECT ROWID
          ,STUDENT_NO
          ,STUDENT_NAME
          ,STUDENT_SSN
          ,STUDENT_ADDRESS
FROM IDX_TEST
WHERE STUDENT_SSN IS NOT NULL;   

-- 테이블에서 사용하고 있는 인덱스 확인
SELECT * FROM USER_IND_COLUMNS WHERE TABLE_NAME = 'IDX_TEST';

--고유인덱스 생성   --이 부분 이름은 원하는데로 지어도 된다
CREATE UNIQUE INDEX IDX_TEST_UNIQUE_STUDENT_NO ON IDX_TEST(STUDENT_NO);
-- 이름은 중복이 될 수도 있다. 지금 이름에서 중복이 있어서 에러 발생. UNIQUE만 빼주면 된다.
--CREATE UNIQUE INDEX IDX_TEST_UNIQUE_STUDENT_NAME ON IDX_TEST(STUDENT_NAME);
CREATE INDEX IDX_TEST_UNIQUE_STUDENT_NAME ON IDX_TEST(STUDENT_NAME);
--고유인덱스 생성 확인 
SELECT * FROM USER_IND_COLUMNS WHERE TABLE_NAME = 'IDX_TEST';
--복합인덱스                                   -- 두 개 이상의 컬럼 지정 가능
CREATE INDEX IDX_TEST_UNIQUE_STUDENT_NAME ON IDX_TEST(STUDENT_NAME, STUDENT_SSN);
--함수식/계산식 인덱스                                      --생년월일 자르기 1~6까지
CREATE INDEX IDX_TEST_UNIQUE_STUDENT_SSN ON IDX_TEST(SUBSTR(STUDENT_SSN,1,6));

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'IDX_TEST';

-- 내림차순으로 정렬 될 수 있도록 인덱스 생성
CREATE INDEX IDX_TEST_STUDENT_SSN ON IDX_TEST(STUDENT_SSN);

-- 인덱스 생성 후 다시 조회
SELECT STUDENT_NAME
     , STUDENT_SSN
  FROM IDX_TEST
 WHERE STUDENT_SSN > '0'; 
 
-- 고유인덱스 삭제
DROP INDEX IDX_TEST_UNIQUE_STUDENT_NO;
DROP INDEX IDX_TEST_UNIQUE_STUDENT_NAME;
DROP INDEX IDX_TEST_UNIQUE_STUDENT_NAME_SSN;
