CREATE SEQUENCE TEMP_SEQ;

--처음에는 CURRVAL 해도 사용이 안됨
SELECT TEMP_SEQ.CURRVAL FROM DUAL;
-- 처음에는 NEXTVAL 먼저 해줘야 한다.
SELECT TEMP_SEQ.NEXTVAL FROM DUAL;
-- 처음 NEXTVAL 하고 CURRVAL 하면 1부터 시작, NEXTVAL->CURRVAL 하면 계속 1씩 증가하는것을 볼 수 있다.

-- SEQUENC의 초기 설정 확인 해 보는 쿼리
SELECT * FROM USER_SEQUENCES;

CREATE TABLE TEMP_T(
    id NUMBER PRIMARY KEY
    ,name VARCHAR(10)
    ,gender CHAR(1) DEFAULT('F') CHECK(gender IN('M','F'))
);

DROP TABLE TEMP_T;
-- 별 다른 설정 하지 않아도 기본으로 저장 되는 것이 DEFAULT인데
--  DEFAULT('Y') 처럼 지정 된 값을 쓸 수 있지만 DEFALUT 뒤에 NEXTVAL을 쓸 수는 없다

INSERT INTO TEMP_T VALUES(1,'aaaa','F');
INSERT INTO TEMP_T VALUES(2,'aaaa','F');
INSERT INTO TEMP_T VALUES(3,'aaaa','F');
-- 지금은 내가 직접 설정 하느라 앞에 값을 1,2,3 식으로 주지만
-시퀀스를 사용하게 되면 시퀀스가 알아서 설정 해 줌
-- 바로 밑에 쿼리처럼 값 자리에 nextval 을 넣어 주면 된다.
INSERT INTO TEMP_TVALUES(TEMP_SEQ.NEXTVAL, 'aaaa','F');

SELECT * FROM TEMP_T;

UPDATE TEMP_T
  SET ID = TEMP_SEQ.NEXTVAL;

SELECT * FROM EMPLOYEES;
SELECT * FROM EMP;

-- USER1연결 상태에서 SYNONYM 하면 에러 발생
--ADMIN으로 계정 변경 후
CREATE SYNONYM EMP FOR EMPLOYEES;
--USER1에게 권한 부여 해 준 다음 SYNONYM 해 주면 CREATE 된다.
GRANT CREATE SYNONYM TO USER1;

-- 시스템계정(ADMIN)으로 전환 후 다음의 구문 
CREATE PUBLIC SYNONYM EMPS FOR USER1.EMPLOYEES;

-- USER1의 EMPLOYEES 검색 해 보는 방법인데 위에 방법으로 검색 권한?을 주는 것.
SELECT * FROM USER1.EMPLOYEES;
SELECT * FROM EMPS;

SELECT * FROM USER_SYNONYMS;
SELECT * FROM ALL_SYNONYMS WHERE OWNER = 'PUBLIC';
SELECT * FROM ALL_SYNONYMS WHERE OWNER = 'PUBLIC' AND TABLE_OWNER NOT IN ('SYS','MDSYS','C##CLOUD$SERVICE','C##ADP$SERVICE');

SELECT * FROM ALL_SYNONYMS
WHERE OWNER = 'PUBLIC'
AND NOT (TABLE_OWNER LIKE '%SYS%'
OR TABLE_OWNER LIKE '%SERVICE%' OR TABLE_OWNER LIKE '%APEX%');

/*
   1, TB_STUDENT 테이블의 데이터를 사용하여 휴학중인 학생의 정보를 저장하기 위한 테이블을 생성한다.
      (테이블 이름은 STUDENT_ANSENCE_TABLE로 한다.)
   2. 생성한 테이블은 ID,학번, 학과코드, 이름, 담당교수 정보를 저장 될 수 있게 한다.
     (ID는 식별값으로 사용하기 위한 컬럼으로 시퀀스를 사용하여 저장 될 수 있게 한다.)
   3. 생성한 테이블은 STD_ABC 이름의 동의어로도 사용 할 수 있도록 만든다.  
      생성한 뷰는  V_STD_ABC 이름의 동의어로도 사용 할 수 있도록 만든다.
*/

SELECT * FROM TB_STUDENT;
SELECT * FROM TB_STUDENT WHERE ABSENCE_YN= 'Y';

/*
CREATE TABLE STUDENT_ABSENCE_TABLE AS
SELECT STUDENT_NO AS 학번
       ,DEPARTMENT_NO AS 학과코드
       ,STUDENT_NAME AS 이름
       ,COACH_PROFESSOR_NO AS 담당교수
FROM TB_STUDENT
WHERE ABSENCE_YN LIKE 'Y%';
*/

DROP TABLE STUDENT_ABSENCE_TABLE;
SELECT* FROM STUDENT_ABSENCE_TABLE;

-- 테이블을 아예 첨부터 생성
CREATE TABLE STUDENT_ABSENCE_TABLE (
    ID NUMBER 
    ,학번 VARCHAR2(10)
    ,학과코드 VARCHAR2(10)
    ,이름 VARCHAR2(50)
    ,담당교수코드 VARCHAR2(10)
);
ALTER TABLE STUDENT_ABSENCE_TABLE ADD CONSTRAINT SAB_ID_PK PRIMARY KEY(ID);
ALTER TABLE STUDENT_ABSENCE_TABLE MODIFY 학번 CONSTRAINT SAB_학번_NN NOT NULL;
ALTER TABLE STUDENT_ABSENCE_TABLE MODIFY 학과코드 CONSTRAINT SAB_학과코드_NN NOT NULL;
ALTER TABLE STUDENT_ABSENCE_TABLE MODIFY 이름 CONSTRAINT SAB_이름_NN NOT NULL;

--SAB = 테이블 앞자리 딴 약자

--SEQUENCE 생성
CREATE SEQUENCE SAB_SEQUENCE;



-- SEQUENCE 생성 후 데이터 추가
INSERT INTO STUDENT_ABSENCE_TABLE (
    SELECT SAB_SEQUENCE.NEXTVAL AS ID 
           ,STUDENT_NO AS 학번
           ,DEPARTMENT_NO AS 학과코드
           ,STUDENT_NAME AS 이름
           ,COACH_PROFESSOR_NO AS 담당교수코드
           FROM TB_STUDENT
    WHERE ABSENCE_YN = 'Y'
);

--권한이 이미 있기 때문에 ADMIN GRANT는 생략

CREATE SYNONYM STD_ABC FOR STUDENT_ABSENCE_TABLE;

--SYNONYM 확인하기
SELECT * FROM STUDENT_ABSENCE_TABLE;
SELECT * FROM STD_ABC;

--VIEW 생성
CREATE VIEW STUDENT_ABSENCE_VIEW AS  
 SELECT     STUDENT_NO AS 학번
           ,DEPARTMENT_NO AS 학과코드
           ,STUDENT_NAME AS 이름
           ,COACH_PROFESSOR_NO AS 담당교수코드
           FROM TB_STUDENT
    WHERE ABSENCE_YN = 'Y';

-- 동의어 생성 
CREATE SYNONYM V_STD_ABC FOR STUDENT_ABSENCE_VIEW;

SELECT * FROM V_STD_ABC;    


--INDEX 실습

SELECT ROWID
       , STUDENT_NO
      , STUDENT_NAME
FROM TB_STUDENT;



