SELECT TO_CHAR(TO_DATE('20-10-13', 'YYYY-MM-DD'))
FROM DUAL;

SELECT EMPNAME AS 직원명
     ,JOBCODE AS 직급코드
     ,SALARY AS 급여
     ,DECODE(JOB_CODE ,'J7', SALARY *0.08, 'J6', SALARY * 0.07, 'J5',SALARY *0.05  SALARY* 0.03)  AS 인상급여
     
 FROM EMP;

 SELECT * FROM EMPLOYEES;

 SELECT DEPT, SUM(SALARY) 합계, FLOOR(AVG(SALARY)) 평균, COUNT(*) 인원수

FROM EMP

WHERE SALARY > 2800000

GROUP BY DEPT

ORDER BY DEPT ASC;

SELECT DEPARTMENT_ID AS 부서코드
      ,SUM(SALARY) AS 급여합계
      ,FLOOR(AVG(SALARY)) AS 급여평균
      ,COUNT(*) AS 인원수
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING FLOOR(AVG(SALARY)) > 1500
ORDER BY DEPARTMENT_ID ASC;

HAVING FLOOR(AVG(SALARY)) > 1500


SELECT ROWNUM
       EMPLOYEE_ID
      ,SALARY
FROM (SELECT * FROM EMPLOYEES ORDER BY SALARY DESC)
WHERE ROWNUM <=3;

SUBQUERY

