-- EMPLOYEES 테이블을 바탕으로 새로운 테이블 생성 후 데이터 추가 작업
-- 추가하는 데이터는 기존 EMPLOYEES 테이블의 데이터를 새로 생성한 테이블 구조에 맞추어 추가
-- 다른 테이블이 가진 데이터 기반으로 데이터를 추가 한다면 일일이 INSERT 작업을 하지 않고서도 
-- 조회 후 추가 하는 형태로 할 수 있다. 
CREATE TABLE EMP_TEMP (
    EMP_ID NUMBER(6)     NOT NULL
    ,NAME  VARCHAR2(20)  NOT NULL
    ,SALARY NUMBER(8,2)
    ,DEPT_ID NUMBER(4)
);
-- 기존 추가 방법
--INSERT INTO EMP_TEMP (EMP_ID, NAME, SALARY, DEPT_ID) VALUES(1,'이름',1000,1)

--서브쿼리 활용해서 추가
INSERT INTO EMP_TEMP (
    SELECT EMPLOYEE_ID
          ,FIRST_NAME ||'' || LAST_NAME
          ,SALARY
          ,DEPARTMENT_ID
FROM EMPLOYEES
);

--다른 테이블과 조인해서 조회해서 새 테이블 생성

CREATE TABLE EMP_TEMP2 (
     EMP_ID NUMBER(6)     NOT NULL
    ,NAME  VARCHAR2(20)  NOT NULL
    ,SALARY NUMBER(8,2)
    ,DEPT_NAME VARCHAR(30) NOT NULL
);

INSERT INTO EMP_TEMP2 (
    SELECT A.EMPLOYEE_ID
          ,A.FIRST_NAME ||'' || LAST_NAME
          ,A.SALARY
          ,B.DEPARTMENT_ID
FROM EMPLOYEES A JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
);

SELECT * FROM EMP_TEMP2;

-- 조회 결과에 맞추어 테이블 생성 및 데이터 추가, INSERT 과정을 굳이 안 써도 된다.
-- 테이블 명 뒤에 꼭 AS를 붙여줘야 한다.
CREATE TABLE EMP_TEMP3 AS
     SELECT A.EMPLOYEE_ID AS EMP_ID
          ,A.FIRST_NAME ||'' || LAST_NAME AS NAME
          ,A.SALARY AS SALARY
          ,B.DEPARTMENT_ID AS DEPT_NAME
FROM EMPLOYEES A JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID;

SELECT * FROM EMP_TEMP3;

-- 다음 작업을 진행하기 위해 기존에 저장 된 데이터 삭제
DELETE FROM EMP_TEMP;
DELETE FROM EMP_TEMP2;
DELETE FROM EMP_TEMP3;

-- INSERT ALL을 사용하여 여러 테이블에 하나의 조회 결과를 동시에 추가 (SELECT 밑에 있는 정보를 추가)
INSERT ALL
 INTO EMP_TEMP VALUES (EMP_ID, NAME, SALARY, DEPT_ID)
 INTO EMP_TEMP2 VALUES (EMP_ID, NAME, SALARY, DEPT_NAME)
SELECT A.EMPLOYEE_ID AS EMP_ID
          ,A.FIRST_NAME ||'' || LAST_NAME AS NAME
          ,A.SALARY AS SALARY
          ,B.DEPARTMENT_ID AS DEPT_ID
          ,B.DEPARTMENT_NAME AS DEPT_NAME
FROM EMPLOYEES A JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID;

SELECT * FROM EMP_TEMP;
SELECT * FROM EMP_TEMP2;

-- 여러 테이블에 조회된 데이터를 추가 할 때 조건에 따라 추가가 되도록 함.( WHEN~THEN)
INSERT ALL
  WHEN SALARY >= 8000 THEN
      INTO EMP_TEMP2 VALUES(EMP_ID, NAME, SALARY, DEPT_NAME)
  WHEN SALARY < 8000 THEN
      INTO EMP_TEMP3 VALUES(EMP_ID, NAME, SALARY, DEPT_NAME)
SELECT A.EMPLOYEE_ID AS EMP_ID
     , A.FIRST_NAME || ' ' || A.LAST_NAME AS NAME
     , A.SALARY AS SALARY
     , B.DEPARTMENT_NAME AS DEPT_NAME
  FROM EMPLOYEES A JOIN DEPARTMENTS B
    ON A.DEPARTMENT_ID = B.DEPARTMENT_ID;

SELECT * FROM EMP_TEMP2;
SELECT * FROM EMP_TEMP3;

DROP TABLE EMP_TEMP;
DROP TABLE EMP_TEMP2;
DROP TABLE EMP_TEMP3;




SELECT * FROM EMPLOYEES;
--테이블 조회 정보
DESC EMPLOYEES;
SELECT * FROM UESR_TAB_COLUMNS WHERE TABLE_NAME = 'EMPLOYEES';

-- 년도별로 학생들의 성적 데이터를 개별 테이블(년도별로 테이블 필요)에 저장 되도록 한다.
-- 코드가 아닌 식별 가능한 값으로 저장되도록 한다.
-- 년도별로 학생들의 성적데이터를 개별 테이블(년도별로 테이블 필요)에 저장되도록 한다.
-- 코드가 아닌 식별 가능한 값으로 저장되도록 한다.
SELECT DISTINCT SUBSTR(TERM_NO, 1, 4) FROM TB_GRADE ORDER BY 1;

CREATE TABLE GRADE_1995 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE 1 = 0;

CREATE TABLE GRADE_1996 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '1996%';

CREATE TABLE GRADE_1997 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '1997%';

CREATE TABLE GRADE_1998 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '1998%';

CREATE TABLE GRADE_1999 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '1999%';

CREATE TABLE GRADE_2000 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '2000%';

CREATE TABLE GRADE_2001 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '2001%';

CREATE TABLE GRADE_2002 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '2002%';

CREATE TABLE GRADE_2003 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '2003%';

CREATE TABLE GRADE_2004 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '2004%';

CREATE TABLE GRADE_2005 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '2005%';

CREATE TABLE GRADE_2006 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '2006%';

CREATE TABLE GRADE_2007 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '2007%';

CREATE TABLE GRADE_2008 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '2008%';

CREATE TABLE GRADE_2009 AS
    SELECT B.TERM_NO AS 학기
         , B.STUDENT_NO AS 학번
         , A.STUDENT_NAME AS 이름
         , B.POINT AS 학점
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '2009%';


INSERT ALL
  WHEN 학기 LIKE '1995%' THEN
      INTO GRADE_1995 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '1996%' THEN
      INTO GRADE_1996 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '1996%' THEN
      INTO GRADE_1997 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '1997%' THEN
      INTO GRADE_1998 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '1998%' THEN
      INTO GRADE_1999 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '1999%' THEN
      INTO GRADE_1996 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '2000%' THEN
      INTO GRADE_2000 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '2001%' THEN
      INTO GRADE_2001 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '2002%' THEN
      INTO GRADE_2002 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '2003%' THEN
      INTO GRADE_2003 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '2004%' THEN
      INTO GRADE_2004 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '2005%' THEN
      INTO GRADE_2005 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '2006%' THEN
      INTO GRADE_2006 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '2007%' THEN
      INTO GRADE_2007 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '2008%' THEN
      INTO GRADE_2008 VALUES(학기, 학번, 이름, 학점)
  WHEN 학기 LIKE '2009%' THEN
      INTO GRADE_2009 VALUES(학기, 학번, 이름, 학점)
SELECT B.TERM_NO AS 학기
     , B.STUDENT_NO AS 학번
     , A.STUDENT_NAME AS 이름
     , B.POINT AS 학점
  FROM TB_STUDENT A JOIN TB_GRADE B
    ON A.STUDENT_NO = B.STUDENT_NO;

SELECT * FROM GRADE_1995;
SELECT * FROM GRADE_1996;
SELECT * FROM GRADE_1997;
SELECT * FROM GRADE_1998;
SELECT * FROM GRADE_1999;
SELECT * FROM GRADE_2000;
SELECT * FROM GRADE_2001;
SELECT * FROM GRADE_2002;
SELECT * FROM GRADE_2003;
SELECT * FROM GRADE_2004;
SELECT * FROM GRADE_2005;
SELECT * FROM GRADE_2006;
SELECT * FROM GRADE_2007;
SELECT * FROM GRADE_2008;
SELECT * FROM GRADE_2009;


DELETE FROM GRADE_1995;
DELETE FROM GRADE_1996;
DELETE FROM GRADE_1997;
DELETE FROM GRADE_1998;
DELETE FROM GRADE_1999;
DELETE FROM GRADE_2000;
DELETE FROM GRADE_2001;
DELETE FROM GRADE_2002;
DELETE FROM GRADE_2003;
DELETE FROM GRADE_2004;
DELETE FROM GRADE_2005;
DELETE FROM GRADE_2006;
DELETE FROM GRADE_2007;
DELETE FROM GRADE_2008;
DELETE FROM GRADE_2009;


DROP TABLE GRADE_1995;
DROP TABLE GRADE_1996;
DROP TABLE GRADE_1997;
DROP TABLE GRADE_1998;
DROP TABLE GRADE_1999;
DROP TABLE GRADE_2000;
DROP TABLE GRADE_2001;
DROP TABLE GRADE_2002;
DROP TABLE GRADE_2003;
DROP TABLE GRADE_2004;
DROP TABLE GRADE_2005;
DROP TABLE GRADE_2006;
DROP TABLE GRADE_2007;
DROP TABLE GRADE_2008;
DROP TABLE GRADE_2009;


SET SERVEROUTPUT ON

BEGIN
   DBMS_OUTPUT.PUT_LINE('HELLO WORLD');
END;

DECLARE
   EMP_ID NUMBER;
   EMP_NAME VARCHAR2(30);
BEGIN 
    EMP_ID := 888;
    EMP_NAME := '배장남';
    DBMS_OUTPUT.PUT_LINE('EMP_ID : '|| EMP_ID);
    DBMS_OUTPUT.PUT_LINE('EMP_NAME  :' || EMP_NAME);
END;