-- 다음 작업을 위한 테이블 생성

CREATE TABLE EMP_TEMP1 AS
     SELECT A.EMPLOYEE_ID AS EMP_ID
          ,A.FIRST_NAME ||'' || LAST_NAME AS NAME
          ,A.SALARY AS SALARY
          ,B.DEPARTMENT_ID AS DEPT_NAME
FROM EMPLOYEES A JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID;

DROP TABLE EMP_TEMP1;
SELECT * FROM EMP_TEMP1;

--업데이트 관련
-- SALARY를 5000으로 바꿔라 (조건X) 
UPDATE EMP_TEMP1
  SET SALARY = 5000;

-- SALARY를 ID 200인 사람만 8000으로 바꿔라 
UPDATE EMP_TEMP1
  SET SALARY = 8000
WHERE EMP_ID = 200;

--업데이트 할 때 서브쿼리 이용 202번이 받은 급여를 200번도 받을 수 있게 수정
--WHERE 절 꼭 확인하고 수정
UPDATE EMP_TEMP1
  SET SALARY = (SELECT SALARY FROM EMP_TEMP1 WHERE EMP_ID = 202 )
WHERE EMP_ID = 200;

UPDATE EMP_TEMP1
  SET (SALARY, DEPT_NAME) = (SELECT SALARY, DEPT_NAME FROM EMP_TEMP1 WHERE EMP_ID = 202 )
WHERE EMP_ID = 200;

-- EMPLOYEES 테이블의 정보를 보면 COMMISSION_PCT가 있는 사원이 있다.
-- 커미션이 있는 사원의 경우 급여 항목이 커미션이 포함 된 급여로 저장 될 수 있게
-- EMP_TEMP1 테이블의 SALARY를 업데이트
/*
 1. UPDATE 는 ROW 단위로 반복 처리 된다.
 2. SET 에 사용되는 값은 단일 값, 단일 ROW로 사용해야 한다.
 */

SELECT * FROM EMP_TEMP1 WHERE EMP_ID BETWEEN 170 AND 179;
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;

UPDATE EMP_TEMP1
  SET SALARY = (SELECT SALARY * (1+COMMISSION_PCT) 
                FROM EMPLOYEES 
                WHERE COMMISSION_PCT IS NOT NULL
                 AND EMPLOYEE_ID = EMP_TEMP1.EMP_ID )
                 -- 단일 값을 줘야하기때문에  AND 값 이렇게 설정
WHERE EMP_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL);

--DELETE도 WHERE로 할 수 있다.
DELETE
  FROM EMP_TEMP1
WHERE EMP_ID IN (SELECT EMPLOYEE_ID
                 FROM EMPLOYEES 
                WHERE COMMISSION_PCT IS NULL);


CREATE TABLE P_TAB (
      ID NUMBER
      ,NAME VARCHAR2(30)
); 
ALTER TABLE P_TAB ADD CONSTRAINT P_TAB_PK PRIMARY KEY (ID);
INSERT ALL
 INTO P_TAB VALUES (ID, NAME)
 SELECT EMPLOYEE_ID AS ID
        ,LAST_NAME AS NAME
FROM EMPLOYEES;

CREATE TABLE C_TAB (
    ID NUMBER
    ,F_ID NUMBER
    ,NAME VARCHAR2(30)
);
ALTER TABLE C_TAB ADD CONSTRAINT C_TAB_ID_PK PRIMARY KEY(ID);
ALTER TABLE C_TAB ADD CONSTRAINT C_TAB_P_TAB_F_ID_FK FOREIGN KEY(F_ID) REFERENCES P_TAB(ID) ;
INSERT INTO C_TAB VALUES (1,100,'aaaa');
INSERT INTO C_TAB VALUES (2,101,'bbbb');
INSERT INTO C_TAB VALUES (3,102,'cccc');

SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME IN ('P_TAB', 'C_TAB');

SELECT * FROM EMPLOYEES;



SELECT * FROM TB_STUDENT;