CREATE OR REPLACE PROCEDURE PROC_EMPLOYEES IS
BEGIN
    FOR R IN (SELECT * FROM EMPLOYEES WHERE ROWNUM <= 3) LOOP
        DBMS_OUTPUT.PUT_LINE(R.EMPLOYEE_ID || ' | ' || CONCAT(R.FIRST_NAME, R.LAST_NAME));
    END LOOP;
END;
/
EXEC PROC_EMPLOYEES;

CREATE OR REPLACE
PROCEDURE PROC_EMPLOYEES(top_n IN NUMBER := 3) IS
BEGIN
    FOR R IN (SELECT * FROM EMPLOYEES WHERE ROWNUM <= top_n) LOOP
        DBMS_OUTPUT.PUT_LINE(R.EMPLOYEE_ID || ' | ' || CONCAT(R.FIRST_NAME, R.LAST_NAME));
    END LOOP;
END;
/
EXEC PROC_EMPLOYEES;
EXEC PROC_EMPLOYEES(5);

CREATE OR REPLACE
PROCEDURE PROC_EMPLOYEES(top_n IN NUMBER := 3, job IN VARCHAR2 := '') IS
BEGIN
    FOR R IN (SELECT * FROM (SELECT *
                               FROM EMPLOYEES
                              WHERE JOB_ID LIKE '%' || job || '%')
                      WHERE ROWNUM <= top_n) LOOP
        DBMS_OUTPUT.PUT_LINE(R.EMPLOYEE_ID || ' | ' || CONCAT(R.FIRST_NAME, R.LAST_NAME));
    END LOOP;
END;
/
EXEC PROC_EMPLOYEES;
EXEC PROC_EMPLOYEES(5);
EXEC PROC_EMPLOYEES(5, 'IT');

SELECT * FROM USER_SOURCE WHERE NAME = 'PROC_EMPLOYEES';


CREATE OR REPLACE
PROCEDURE PROC_STD_PRO_INFO(hidden IN BOOLEAN := TRUE) IS
    HIDDEN_YN   BOOLEAN;
BEGIN
    HIDDEN_YN := hidden;
    FOR R IN (SELECT * FROM V_STD_PROF_INFO WHERE ROWNUM <= 10) LOOP
        DBMS_OUTPUT.PUT(R.NAME || ' | ');

        IF HIDDEN_YN THEN
            DBMS_OUTPUT.PUT(SUBSTR(R.SSN, 1, 8) || '******' || ' | ');
        ELSE
            DBMS_OUTPUT.PUT(R.SSN);
        END IF;

        DBMS_OUTPUT.PUT(R.ADDR);
        DBMS_OUTPUT.PUT_LINE('');
    END LOOP;
END;
/

EXEC PROC_STD_PRO_INFO;
EXEC PROC_STD_PRO_INFO(FALSE);


-- OUT 매개변수 있는 프로시저 생성
-- OUT = 값을 보내는 것.
CREATE OR REPLACE       --TOTAL = 지역변수, OUT은 RET_VAL 공간을 만든곳에 넣어주는 것.
PROCEDURE PROC_EMPLOYEES(TOP_N IN NUMBER:=3 total out NUMBER) IS 
BEGIN
    total :=0;
    FOR R IN(SELECT * FROM WHERE ROWNUM <= TOP_N) LOOP 
    DBMS_OUTPUT.PUT_LINE(R.EMPLOYEE_ID || '|' ||CONCAT(R.FIRST_NAME, R.LAST_NAME));
    total := total + R.SALARY;
    END LOOP;
END;
/
-- 전역 변수
VARIABLE ret_val NUMBER;  -- (:) <-바인드
EXEC PROC_EMPLOYEES(5, :ret_val); --OUT 되는 변수 앞에는 콜론(:) 필수!!
PRINT ret_val;

DECLARE
  ret_val NUMBER;
BEGIN
   PROC_EMPLOYEES(5, :ret_val);
   DBMS_OUTPUT.PUT_LINE(ret_val);
END;
/
SELECT * FROM USER_SOURCE WHERE NAME = 'PROC_EMPLOYEES';