SET SERVEROUTPUT ON ;

BEGIN
  DBMS_OUTPUT.PUT_LINE('HELLO PL/SQL');
END;
/
DECLARE
   ID NUMBER := 5 ;
   NAME VARCHAR2(10) := '온달이';
BEGIN
   ID := ID+ 1;
   DBMS_OUTPUT.PUT_LINE('번호 : ' || ID);
   DBMS_OUTPUT.PUT_LINE('이름: ' || NAME);
END;
/

DECLARE
  VAL NUMBER;
BEGIN
  VAL := &VAL;
  DBMS_OUTPUT.PUT_LINE('입렵란 정수값 : ' || VAL);
END;
/

DECLARE
  INPUT_NUM NUMBER;
  VAL NUMBER;
BEGIN
  VAL := &INPUT_NUM;
  IF (MOD(VAL,2)=0 ) THEN  -- MOD 나머지 계산
  DBMS_OUTPUT.PUT_LINE('짝수를 입력했습니다.');
  ELSIF (MOD(VAL,2)=1 ) THEN
    DBMS_OUTPUT.PUT_LINE('홀수를 입력했습니다.');
    END IF;
END;
/

DECLARE
  INPUT_NUM NUMBER;
  VAL NUMBER;
BEGIN
  VAL := &INPUT_NUM;
  LOOP  -- 무한반복
    DBMS_OUTPUT.PUT_LINE('반복문 입니다. :' || VAL);
    VAL := VAL -1;  -- VAL 값에서 -1씩 빼면서 반복 
    IF VAL = 0 THEN EXIT ;  --0이 되면 반복문 종료 
    END IF;
END LOOP;
END;
/
BEGIN 
   FOR I IN 0..3 LOOP   -- 0~3까지 반복 되는 것.
     DBMS_OUTPUT.PUT_LINE('반복문 입니다. :' || I);
   END LOOP;
END;
/

BEGIN 
   FOR I IN REVERSE 0..3 LOOP  --3~0까지 반복 위에 반대로 되는것 REVERSE
     DBMS_OUTPUT.PUT_LINE('반복문 입니다. : ' || I);
   END LOOP;
END;
/

DECLARE
  VAL NUMBER;
BEGIN
  VAL := 0;
  WHILE VAL < 3 LOOP
    DBMS_OUTPUT.PUT_LINE('WHILE 반복문 입니다. :' || VAL );
    VAL := VAL +1;
    END LOOP;
END;
/

DECLARE
   --FNAME VARCHAR2(20);
   --LNAME VARCHAR2(20);
   --SALARY NUMBER;
   FNAME EMPLOYEES.FIRST_NAME%TYPE;
   LNAME EMPLOYEES.LAST_NAME%TYPE;
   SALARY EMPLOYEES.SALARY%TYPE;
BEGIN
  SELECT FIRST_NAME
        , LAST_NAME
        , SALARY
    INTO FNAME,LNAME,SALARY
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 100;

    DBMS_OUTPUT.PUT_LINE('성 : ' || FNAME);
    DBMS_OUTPUT.PUT_LINE('이름 : ' || LNAME);
    DBMS_OUTPUT.PUT_LINE('급여 : ' || SALARY);
END;
/

DECLARE 
  EMP EMPLOYEES%ROWTYPE;
BEGIN
  SELECT *
   INTO EMP
   FROM EMPLOYEES
   WHERE EMPLOYEE_ID = 100;

   DBMS_OUTPUT.PUT_LINE('성 : ' || EMP.LAST_NAME);
   DBMS_OUTPUT.PUT_LINE('이름 : ' || EMP.FIRST_NAME);
   DBMS_OUTPUT.PUT_LINE('급여액 : ' || EMP.SALARY);
END;
/

DECLARE
   EMP EMPLOYEES%ROWTYPE;
BEGIN
    SELECT * 
    INTO EMP
    FROM EMPLOYEES
    WHERE SALARY >= 10000;

   DBMS_OUTPUT.PUT_LINE('성 : ' || EMP.LAST_NAME);
   DBMS_OUTPUT.PUT_LINE('이름 : ' || EMP.FIRST_NAME);
   DBMS_OUTPUT.PUT_LINE('급여액 : ' || EMP.SALARY);
-- 예외처리
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('해당 데이터가 존재하지 않습니다.');
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('너무 많은 행 데이터가 있습니다.');

END;
/

DROP VIEW V_DEPT_INFO;


CREATE VIEW V_DEPT_INFO AS
    SELECT A.DEPARTMENT_NO AS 학과코드
         , A.DEPARTMENT_NAME AS 학과명
         , A.CATEGORY AS 분류
         , A.OPEN_YN AS 개설여부
         , A.CAPACITY AS 정원
         , COUNT(*) AS 현재인원
      FROM TB_DEPARTMENT A JOIN TB_STUDENT B
        ON A.DEPARTMENT_NO = B.DEPARTMENT_NO
     GROUP BY A.DEPARTMENT_NO, A.DEPARTMENT_NAME
            , A.CATEGORY, A.OPEN_YN, A.CAPACITY;

DECLARE
    R V_DEPT_INFO%ROWTYPE;
    DEPT_CODE V_DEPT_INFO.DEPARTMENT_NO%TYPE;
BEGIN
    -- TB_STUDENT, TB_DEPARTMENT, ...
    -- 학과번호를 입력하면 해당 학과의 이름, 카테고리, 개설여부, 최대인원, 실인원
    -- 정보가 출력될 수 있도록 한다.
    SELECT *
      INTO R
      FROM V_DEPT_INFO
     WHERE 학과코드 = &DEPT_CODE;

    DBMS_OUTPUT.PUT_LINE(R.학과명 || ' | ' || R.분류 || ' | ' || R.개설여부 || ' | ' || R.정원  || ' | ' || R.현재인원);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('해당 데이터가 존재하지 않습니다.');
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('너무 많은 행 데이터가 있습니다.');
END;
/


SELECT * FROM TB_DEPARTMENT; 


SELECT A.DEPARTMENT_NAME
         , A.CATEGORY
         , A.OPEN_YN
         , A.CAPACITY
         , COUNT(*)
      FROM TB_DEPARTMENT A JOIN TB_STUDENT B
        ON A.DEPARTMENT_NO = B.DEPARTMENT_NO
     WHERE A.DEPARTMENT_NO = 1
     GROUP BY A.DEPARTMENT_NAME, A.CATEGORY, A.OPEN_YN, A.CAPACITY;

DESC TB_DEPARTMENT;

SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_STUDENT;

DECLARE
  --TYPE먼저 정의해준다
  TYPE NAME_ARRAY IS TABLE OF V_DEPT_INFO.학과명%TYPE INDEX BY BINARY_INTEGER;
  ARR_NAME NAME_ARRAY;
  IDX BINARY_INTEGER := 0;

BEGIN    --반복문, SELECT로 LOOP 하겠다
    
 FOR R IN (SELECT * FROM V_DEPT_INFO) LOOP
     IDX := IDX +1;
     ARR_NAME(IDX) := R.학과명;
END LOOP;

FOR I IN 1..IDX LOOP
  DBMS_OUPPUT.PUT_LINE(ARR_NAME(I));
END LOOP;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('해당 데이터가 존재하지 않습니다.');
END;
/
