-- 모든 조회 결과에는 코드가 아닌 식별 가능한 값도 조회 되어야 한다.

SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM REGIONS;
SELECT * FROM COUNTRIES;
SELECT * FROM LOCATIONS;

-- 1. 매니저가 존재하는 부서의 사원들을 조회
--  (DEPARTMENTS, EMPLOYEES)
--서브쿼리 이용
SELECT EMPLOYEE_ID 
      ,FIRST_NAME
      ,LAST_NAME
      ,DEPARTMENT_ID
      ,(SELECT DEPARTMENT_NAME FROM DEPARTMENTS B WHERE B.DEPARTMENT_ID = A.DEPARTMENT_ID) AS DEPARTMENT_NAME
FROM EMPLOYEES A
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                        FROM DEPARTMENTS 
                        WHERE MANAGER_ID IS NOT NULL);

-- JOIN 이용
SELECT A.EMPLOYEE_ID AS 사원코드
      ,A.DEPARTMENT_ID AS 부서코드
      ,CONCAT(FIRST_NAME, '' || LAST_NAME) AS 사원명
      ,B.DEPARTMENT_NAME AS 부서명
      ,B.MANAGER_ID AS 관리자코드
FROM EMPLOYEES A JOIN DEPARTMENTS B
ON (A.MANAGER_ID = B.MANAGER_ID)
WHERE B.MANAGER_ID IS NOT NULL--  NULL값은 뺴주세요~
ORDER BY 1;    

-- 2. 유럽, 아메리카 , 아시아, 중앙아시아/아프리카 지역 (REGIONS)에 있는 부서의 수를 조회
--  (REGIONS, COUNTRIES)
SELECT *
      FROM DEPARTMENTS A JOIN LOCATIONS B
      ON A.LOCATION_ID = B.LOCATION_ID
      JOIN COUNTRIES C 
      ON B.COUNTRY_ID = C.COUNTRY_ID;






SELECT * FROM REGIONS;
SELECT * FROM COUNTRIES;

SELECT A.COUNTRY_NAME AS 국가명
      ,COUNT(B.REGION_ID) AS 지역코드
FROM COUNTRIES A JOIN REGIONS B
ON A.REGION_ID = B.REGION_ID
GROUP BY COUNTRY_ID, COUNTRY_NAME;

-- 3. 모든 부서의 위치(주소) 조회
--   (COUNTRIES, REGIONS, LOCATIONS, DEPARTMENTS)
SELECT * FROM DEPARTMENTS;
SELECT * FROM REGIONS;
SELECT * FROM COUNTRIES;
SELECT * FROM LOCATIONS;

SELECT DEPARTMENT_ID AS 부서코드
       ,DEPARTMENT_NAME AS 부서명
       ,LOCATION_ID AS 주소코드
       ,(SELECT STREET_ADDRESS FROM LOCATIONS B WHERE B.LOCATION_ID = A.LOCATION_ID) AS 주소
 FROM DEPARTMENTS A ;

 SELECT A.DEPARTMENT_NAME AS 부서명
     , D.REGION_NAME || ' ' ||
       C.COUNTRY_NAME  || ' ' ||
       B.STATE_PROVINCE  || ' ' ||
       B.CITY  || ' ' ||
       B.STREET_ADDRESS  || ' ' ||
       B.POSTAL_CODE AS 영문주소
  FROM DEPARTMENTS A JOIN LOCATIONS B
    ON A.LOCATION_ID = B.LOCATION_ID
  JOIN COUNTRIES C
    ON B.COUNTRY_ID = C.COUNTRY_ID
  JOIN REGIONS D
    ON C.REGION_ID = D.REGION_ID;

-- 4. 아프리카 지역에 해당하는 부서와 소속 사원들을 조회
--  (COUNTRIES, REGIONS, LOCATIONS, DEPARTMENTS, EMPLOYEES )

SELECT B.DEPARTMENT_NAME AS 부서명
     , A.FIRST_NAME || ' ' || A.LAST_NAME AS 이름
  FROM EMPLOYEES A JOIN DEPARTMENTS B
    ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
  JOIN LOCATIONS C
    ON B.LOCATION_ID = C.LOCATION_ID
  JOIN COUNTRIES D
    ON C.COUNTRY_ID = D.COUNTRY_ID
  JOIN REGIONS E
    ON D.REGION_ID = E.REGION_ID
 WHERE D.REGION_ID = 1
 ORDER BY 1;

-- 5. 소속 지역별 평균급여 랭크 조회(지역은 대륙단위로 묶어서 한다.)
--  (COUNTRIES, REGIONS, LOCATIONS, DEPARTMENTS, EMPLOYEES)
SELECT RANK() OVER(ORDER BY AVG(A.SALARY) DESC) AS 랭킹
     , TRUNC(AVG(A.SALARY)) AS 평균급여
     , E.REGION_NAME AS 국가명
  FROM EMPLOYEES A JOIN DEPARTMENTS B
    ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
  JOIN LOCATIONS C
    ON B.LOCATION_ID = C.LOCATION_ID
  JOIN COUNTRIES D
    ON C.COUNTRY_ID = D.COUNTRY_ID
  JOIN REGIONS E
    ON D.REGION_ID = E.REGION_ID
 GROUP BY E.REGION_NAME;

-- 6. 국가별 평균급여 랭크 조회
--    (COUNTRIES, LOCATIONS, DEPARTMENTS, EMPLOYEES)
SELECT RANK() OVER(ORDER BY AVG(A.SALARY) DESC) AS 랭킹
     , TRUNC(AVG(A.SALARY)) AS 평균급여
     , D.COUNTRY_NAME AS 국가명
  FROM EMPLOYEES A JOIN DEPARTMENTS B
    ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
  JOIN LOCATIONS C
    ON B.LOCATION_ID = C.LOCATION_ID
  JOIN COUNTRIES D
    ON C.COUNTRY_ID = D.COUNTRY_ID
 GROUP BY D.COUNTRY_NAME;

-- 7. 국가별/부서별 평균급여 조회(전체 평균 및 국가 단위 평균, 부서 단위 평균의 통계가 필요)
--    (COUNTRIES, LOCATIONS, DEPARTMENTS, EMPLOYEES)
SELECT TRUNC(AVG(A.SALARY)) AS 평균급여
     , D.COUNTRY_NAME AS 국가명
     , B.DEPARTMENT_NAME AS 부서명
  FROM EMPLOYEES A JOIN DEPARTMENTS B
    ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
  JOIN LOCATIONS C
    ON B.LOCATION_ID = C.LOCATION_ID
  JOIN COUNTRIES D
    ON C.COUNTRY_ID = D.COUNTRY_ID
 GROUP BY CUBE(D.COUNTRY_NAME, B.DEPARTMENT_NAME);