-- JOIN : 2개 이상의 테이블에서 데이터를 조회하기 위해 사용하는 구문
--        집합 구문과는 다르게 두 쿼리 결과에 대한 무조건적인 집합셋(쿼리셋)을 구하는 것이 아닌
--        쿼리 결과에 대한 결합 조건이 있다. JOIN 시켜 주는 것.
--        집합 구문에서는 행(로우) 데이터에 대한 추가가 이루어지지만,
--        JOIN은 열(컬럼) 데이터에 대한 추가가 이루어 진다.

SELECT * 
FROM EMPLOYEES JOIN DEPARTMENTS
ON (EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID);

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

-- JOIN을 수행하는 테이블의 컬럼이 동일한 이름을 사용하는 경우 테이블명.컬럼명 으로 구분시킨다.
SELECT EMPLOYEES.EMPLOYEE_ID AS 사원코드,
       CONCAT(EMPLOYEES.FIRST_NAME, '' || EMPLOYEES.LAST_NAME) AS 사원명,
       EMPLOYEES.DEPARTMENT_ID AS 부서코드,
       DEPARTMENTS.DEPARTMENT_NAME AS 부서명
FROM EMPLOYEES JOIN DEPARTMENTS
ON (EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID);

 
-- JOIN 쿼리문 작성 시 테이블 명을 명시 해주면 좀 더 정확하게 표시 가능.
-- 테이블 명 다 작성해주기 좀 번거로우니깐 A B 등으로 간단하게 별칭 부여 해 줄 수 있다.
SELECT A.EMPLOYEE_ID AS 사원코드,
       CONCAT(A.FIRST_NAME, '' || A.LAST_NAME) AS 사원명,
       A.DEPARTMENT_ID AS 부서코드,
       B.DEPARTMENT_NAME AS 부서명
FROM EMPLOYEES A JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID);

-- JOIN 조건의 컬럼명이 동일 한 경우에만 USING을 사용하여 결합 시킬 수 있다.
-- 대신 해당 컬럼명 앞에는 테이블명. 을 붙여주면 안된다.
-- USING(컬럼명) 한번만 써 주면 된다.
SELECT A.EMPLOYEE_ID AS 사원코드,
       CONCAT(A.FIRST_NAME, '' || A.LAST_NAME) AS 사원명,
       DEPARTMENT_ID AS 부서코드,
       B.DEPARTMENT_NAME AS 부서명
FROM EMPLOYEES A JOIN DEPARTMENTS B
USING (DEPARTMENT_ID);

-- 2개 이상인 테이블에 대한 JOIN

SELECT A.EMPLOYEE_ID AS 사원코드,
       CONCAT(A.FIRST_NAME, '' || A.LAST_NAME) AS 사원명,
       DEPARTMENT_ID AS 부서코드,
       B.DEPARTMENT_NAME AS 부서명,
       JOB_ID AS 직업코드,
       C.JOB_TITLE AS 직업명
FROM EMPLOYEES A JOIN DEPARTMENTS B
USING (DEPARTMENT_ID)
     JOIN JOBS C
USING (JOB_ID);


SELECT * FROM EMPLOYEES;

SELECT * FROM JOBS;

-- 아래의 테이블의 DEPARTMENT_NO, COACH_PROFESSOR_NO를 활용하여 학과명, 교수명 컬럼이
-- 조회 될 수 있도록 JOIN을 사용
SELECT * FROM TB_STUDENT;

SELECT A.STUDENT_NO,
       A.STUDENT_NAME, 
       A.DEPARTMENT_NO, 
       B.DEPARTMENT_NAME,
       A.COACH_PROFESSOR_NO, 
       C.PROFESSOR_NAME
FROM TB_STUDENT A JOIN TB_DEPARTMENT B
ON A.DEPARTMENT_NO = B.DEPARTMENT_NO
JOIN TB_PROFESSOR C 
ON A.COACH_PROFESSOR_NO = C.PROFESSOR_NO;




SELECT * FROM ALL_ALL_TABLES WHERE OWNER = 'USER1';

SELECT * FROM TB_DEPARTMENT;

SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID,
       FIRST_NAME,
       LAST_NAME,
       DEPARTMENT_ID
FROM EMPLOYEES WHERE EMPLOYEE_ID BETWEEN 175 AND 180;

-- OUTER JOIN : 일반 JOIN 과는 다르게 결합 조건에 부합하는 데이터가 없어도 조회 결과로 나올 수 있게 한다.
               
SELECT A.EMPLOYEE_ID,
       A.FIRST_NAME,
       A.LAST_NAME,
       A.DEPARTMENT_ID,
       B.DEPARTMENT_NAME
     --왼쪽(EMPLOYEES)에 내용이 있고 오른쪽에 값이 없어도. JOIN을 해줘라
FROM EMPLOYEES A LEFT OUTER JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
WHERE EMPLOYEE_ID BETWEEN 175 AND 180;  -- 많은 자료 중에 필요한 자료만 보기 위해 WHERE로 조건을 걸어줌

-- 컬럼명 조회 방법
SELECT * FROM USER_TAB_COLUMNS;

WITH L_TB AS (
     SELECT 1 AS ID , '가' AS NAME FROM DUAL
     UNION ALL
     SELECT 2 AS ID , '나' AS NAME FROM DUAL
     UNION ALL
     SELECT 3 AS ID , '다' AS NAME FROM DUAL
), R_TB AS (
     SELECT 1 AS ID , '라' AS NAME FROM DUAL
     UNION ALL
     SELECT 2 AS ID , '마' AS NAME FROM DUAL
     UNION ALL
     SELECT 4 AS ID , '바' AS NAME FROM DUAL
     
)
SELECT * FROM L_TB A INNER JOIN R_TB B
ON A.ID = B.ID;

-- NON_EQU JOIN : 일정 범위에 해당 하는 열을 기준으로 조인을 하는 형식
-- ON A.SALARY BETWEEN B.MIN_SALARY AND B.MAX_SALARY  
-- 이러한 형태로 사용한다.

SELECT * FROM JOBS;
SELECT * FROM EMPLOYEES;

SELECT A.EMPLOYEE_ID,
       A.FIRST_NAME,
       A.LAST_NAME,
       A.SALARY,
       B.JOB_ID,
       B.JOB_TITLE
FROM EMPLOYEES A JOIN JOBS B
ON A.SALARY BETWEEN B.MIN_SALARY AND B.MAX_SALARY 
ORDER BY 1;

--SELF JOIN : 서로 다른 테이블간 조인이 아닌 동일한 테이블을 이용하여 조인을 하는 형식

SELECT A.EMPLOYEE_ID AS 사번, 
       A.FIRST_NAME || '' || A.LAST_NAME AS 사원명,
       B.MANAGER_ID AS 관리자사번,
       B.FIRST_NAME  ||  '' || B.LAST_NAME AS 관리자명
FROM EMPLOYEES A JOIN EMPLOYEES B
ON A.MANAGER_ID = B.EMPLOYEE_ID
ORDER BY 1;

SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS WHERE PREATTENDING_CLASS_NO IS NOT NULL;
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_GRADE;


-- 교수별 담당 과목 수가 얼마나 되는지(COUNT) 해당 교수의 이름과 같이 조회를 하시오.
-- 교수코드로는 그 사람이 누군지 알 수 없기 때문에 JOIN 해 준다.
--  우선 수량체크 먼저
SELECT A.PROFESSOR_NO AS 교수코드,
       COUNT(A.CLASS_NO) AS 총과목수
FROM TB_CLASS_PROFESSOR A
GROUP BY A.PROFESSOR_NO;
       
-- 이 결과를 바탕으로 TB_PROFESSOR랑 JOIN
SELECT A.PROFESSOR_NO AS 교수코드,
       B.PROFESSOR_NAME AS 교수명,  --마찬가지로 GROUPBY 해줘야한다.
       COUNT(A.CLASS_NO) AS 총과목수
FROM TB_CLASS_PROFESSOR A JOIN TB_PROFESSOR B
ON A.PROFESSOR_NO = B.PROFESSOR_NO
GROUP BY A.PROFESSOR_NO, B.PROFESSOR_NAME;

--이건 내가 한거. 나는 COUNT를 써주지 않음 ㅠ
SELECT A.CLASS_NO AS 과목번호,
       B.PROFESSOR_NO AS 교수번호,
       B.PROFESSOR_NAME AS 교수명
FROM TB_CLASS_PROFESSOR A LEFT OUTER JOIN TB_PROFESSOR B
ON A.PROFESSOR_NO = B.PROFESSOR_NO;

-- 학과별 배정 된 교수의 인원이 얼마나 되는지(COUNT) 해당 학과명과 같이 조회를 하시오.

SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;

SELECT A.DEPARTMENT_NO AS 학과코드,
       A.DEPARTMENT_NAME AS 학과명,
       COUNT(B.PROFESSOR_NO) AS 교수인원  
FROM TB_DEPARTMENT A JOIN TB_PROFESSOR B
ON A.DEPARTMENT_NO = B.DEPARTMENT_NO
GROUP BY A.DEPARTMENT_NO, A.DEPARTMENT_NAME
ORDER BY 교수인원 DESC;


SELECT A.CLASS_NO AS 학과번호,
       A.CLASS_NAME AS 학과명,
       B.PROFESSOR_NO AS 교수번호
FROM TB_CLASS A JOIN TB_CLASS_PROFESSOR B
ON A.CLASS_NO = B.CLASS_NO;

-- 모든 학생들의 학점을 출력하시오.(단, 코드가 아닌 식별 가능한 이름으로 출력)
-- 이건 내가 한거..
SELECT A.STUDENT_NO AS 학생번호,
       A.STUDENT_NAME AS 학생명,
       B.POINT AS 학점
FROM TB_STUDENT A  JOIN TB_GRADE B
ON A.STUDENT_NO = B.STUDENT_NO;

-- 내가 한거에서 수정. JOIN을 한번 더 해서 CLASS_NAME까지 추가 해 준다.
SELECT A.STUDENT_NO AS 학생번호,
       A.STUDENT_NAME AS 학생명,
       B.POINT AS 학점,
       C.CLASS_NAME
FROM TB_STUDENT A JOIN TB_GRADE B
ON A.STUDENT_NO = B.STUDENT_NO
JOIN TB_CLASS C
ON B.CLASS_NO = C.CLASS_NO;


SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM REGIONS;
SELECT * FROM COUNTRIES;
SELECT * FROM LOCATIONS;