-- SELECT 절에 SUBQUERY 사용 -> SCALAR(스칼라) SUBQUERY
-- SCALAR : 단일 값 OR 정해진 값 이라고 보면 된다.
SELECT EMPLOYEE_ID,
       FIRST_NAME,
       LAST_NAME,
       EMAIL,
       PHONE_NUMBER,
       HIRE_DATE,
       JOB_ID, 
       (SELECT JOB_TITLE FROM JOBS B WHERE B.JOB_ID = A.JOB_ID) AS JOB_TITLE,--하나의 컬럼을 꼭 지정해서 넣어줘야 한다.
       SALARY,
       COMMISSION_PCT,
       MANAGER_ID, 
       DEPARTMENT_ID,
       (SELECT DEPARTMENT_NAME FROM DEPARTMENTS C WHERE C.DEPARTMENT_ID = A.DEPARTMENT_ID) AS DEPARTMENT_NAME
 FROM EMPLOYEES A ;

-- WHERE 절에 SUBQUERY 사용 -> 상호연관 SUBQUERY 

SELECT *
FROM EMPLOYEES
WHERE SALARY >= (SELECT AVG(SALARY) FROM EMPLOYEES );

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (SELECT DISTINCT MANAGER_ID FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL);

-- FROM 절에 SUBQUERY 사용 -> INLINE VIEW(인라인뷰) 라고 함.
SELECT * 
FROM  (SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES);
-- 괄호 안에 것들로 테이블 생성 후 그것들을 SELECT 하겠다

-- WITH를 사용하면 임시로 이름을 지정한 테이블 생성 가능
WITH TEMP AS (
    SELECT EMPLOYEE_ID,
           FIRST_NAME,
           LAST_NAME
    FROM EMPLOYEES
)
SELECT * FROM TEMP;

-- 랭킹 조회
SELECT * 
FROM (SELECT EMPLOYEE_ID,
             FIRST_NAME,
             LAST_NAME,
             SALARY,
             RANK() OVER (ORDER BY SALARY DESC) AS "RANK"
FROM EMPLOYEES
ORDER BY SALARY DESC);

-- WHERE로 조건 주기
SELECT * 
FROM (SELECT EMPLOYEE_ID,
             FIRST_NAME,
             LAST_NAME,
             SALARY,
             RANK() OVER (ORDER BY SALARY DESC) AS "RANK"
FROM EMPLOYEES)
WHERE "RANK" <= 10;

--DENSE RANK : 똑같은 값이 나와도 랭킹값이 올라가지 않고 같은 랭킹값이 나오는 것.
SELECT * 
FROM (SELECT EMPLOYEE_ID,
             FIRST_NAME,
             LAST_NAME,
             SALARY,
             DENSE_RANK() OVER (ORDER BY SALARY DESC) AS "RANK"
FROM EMPLOYEES)
WHERE "RANK" <= 10;



-- 모든 조회 결과에는 코드가 아닌 식별 가능한 값도 조회 되어야 한다.

SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM REGIONS;
SELECT * FROM COUNTRIES;
SELECT * FROM LOCATIONS;

-- 1. 매니저가 존재하는 부서의 사원들을 조회
--  (DEPARTMENTS, EMPLOYEES)
SELECT A.DEPARTMENT_ID AS 부서코드
      ,CONCAT(FIRST_NAME, '' || LAST_NAME) AS 사원명
      ,B.DEPARTMENT_NAME AS 부서명
      ,B.MANAGER_ID AS 관리자코드
FROM EMPLOYEES A JOIN DEPARTMENTS B
ON (A.MANAGER_ID = B.MANAGER_ID);
    
-- 2. 유럽, 아메리카 , 아시아, 중앙아시아/아프리카 지역 (REGIONS)에 있는 부서의 수를 조회
--  (REGIONS, COUNTRIES)
SELECT * FROM REGIONS;
SELECT * FROM COUNTRIES;

SELECT A.COUNTRY_NAME AS 국가명
      ,COUNT(B.REGION_ID) AS 지역코드
FROM COUNTRIES A JOIN REGIONS B
ON A.REGION_ID = B.REGION_ID
GROUP BY COUNTRY_ID, COUNTRY_NAME;

-- 3. 모든 부서의 위치(주소) 조회
--   (COUNTRIES, REGIONS, LOCATIONS, DEPARTMENTS)
SELECT * FROM DEPARTMENTS;
SELECT * FROM REGIONS;
SELECT * FROM COUNTRIES;
SELECT * FROM LOCATIONS;

SELECT DEPARTMENT_ID AS 부서코드
       ,DEPARTMENT_NAME AS 부서명
       ,LOCATION_ID AS 주소코드
       ,(SELECT STREET_ADDRESS FROM LOCATIONS B WHERE B.LOCATION_ID = A.LOCATION_ID) AS 주소
 FROM DEPARTMENTS A ;

-- 4. 아시아 지역에 해당하는 부서와 소속 사원들을 조회
--  (COUNTRIES, REGIONS, LOCATIONS, DEPARTMENTS, EMPLOYEES )

WITH ASIA AS (
    SELECT ,
           FIRST_NAME,
           LAST_NAME
    FROM EMPLOYEES
)
SELECT * FROM TEMP;

-- 5. 소속 지역별 평균급여 랭크 조회(지역은 대륙단위로 묶어서 한다.)
--  (COUNTRIES, REGIONS, LOCATIONS, DEPARTMENTS, EMPLOYEES)
SELECT * 
FROM (SELECT ,
             FIRST_NAME,
             LAST_NAME,
             SALARY,
             DENSE_RANK() OVER (ORDER BY SALARY DESC) AS "RANK"
FROM LOCATIONS )
WHERE "RANK" <= 10;

