CREATE TABLE DEPARTMENT(
    DEPTCODE NUMBER PRIMARY KEY
   ,DEPTNAME NVARCHAR2(10) NOT NULL
);

CREATE TABLE EMPLOYEE(
    EMPNO NUMBER PRIMARY KEY
    ,EMPNAME VARCHAR(10) NOT NULL
    ,DEPTNO NUMBER REFERENCES DEPARTMENT(DEPTCODE)
);

DROP TABLE DEPARTMENT;
DROP TABLE EMPLOYEE;

SELECT EMPNO
      ,EMPNAME
      ,DEPTNO
      ,DEPTNAME
FROM EMPLOYEE 
JOIN DEPARTMENT ON DEPTNO = DEPTCODE; 
