SELECT EMPLOYEE_ID AS 사원번호
      ,CONCAT(FIRST_NAME, ''|| LAST_NAME) AS 이름
      ,DEPARTMENT_ID AS 부서명
FROM EMPLOYEES;

SELECT DISTINCT DEPARTMENT_ID 
               ,MANAGER_ID
               ,CONCAT(FIRST_NAME, '' || LAST_NAME)
FROM EMPLOYEES;

SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME AS 성
      ,LAST_NAME AS 이름
      ,SALARY AS 급여
      ,SALARY*12 AS 연봉
      ,COMMISSION_PCT AS 인센티브
      ,SALARY*12+COMMISSION_PCT AS 인센포함연봉
FROM EMPLOYEES
ORDER BY COMMISSION_PCT ASC;

SELECT DISTINCT JOB_ID
FROM EMPLOYEES;

SELECT EMPLOYEE_ID AS 사원번호
      ,CONCAT(FIRST_NAME, '' || LAST_NAME) AS 사원명
      ,MANAGER_ID AS 매니져코드
      ,SALARY AS  급여
      ,COMMISSION_PCT AS 인센티브
      ,DEPARTMENT_ID AS 부서코드
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID DESC, 사원명 ASC; 

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID <= 105 AND JOB_ID = 'IT_PROG';

SELECT * FROM EMPLOYEES
WHERE JOB_ID NOT IN( 'IT_PROG', 'AC_MGR', 'AD_VIP') ;

SELECT * FROM EMPLOYEES
WHERE NOT SALARY * 12 >= 100000 ;

SELECT * FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 7000 AND 12000;

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'D%';

SELECT * FROM EMPLOYEES 
WHERE COMMISSION_PCT IS NOT NULL;

SELECT * FROM EMPLOYEES
WHERE LAST_NAME LIKE 'S%';

SELECT EMPLOYEE_ID AS 사원번호
      ,CONCAT(FIRST_NAME, ''|| LAST_NAME) AS 사원명
      ,JOB_ID AS 직무코드
      ,SALARY AS 급여
      ,DEPARTMENT_ID 부서코드
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(60,90) AND SALARY >= 9000;

SELECT EMPLOYEE_ID AS 사원번호
      ,CONCAT(FIRST_NAME, ''|| LAST_NAME) AS 사원명
      ,JOB_ID AS 직무코드
      ,SALARY AS 급여
      ,DEPARTMENT_ID 부서코드
FROM EMPLOYEES
WHERE SALARY > 9000 OR SALARY < 10000;

SELECT EMPLOYEE_ID AS 사원번호
      ,FIRST_NAME AS 성
      ,LAST_NAME AS 이름
      ,SALARY AS 급여
      ,DEPARTMENT_ID 부서코드
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%S%' AND SALARY NOT BETWEEN 6000 AND 9000;

SELECT EMPLOYEE_ID AS 사원코드
      ,FIRST_NAME AS 성
      ,LAST_NAME AS 이름
      ,JOB_ID AS 직무코드
      ,MANAGER_ID AS 매니져코드
      ,SALARY AS 급여
      ,COMMISSION_PCT AS 인센티브
      ,DEPARTMENT_ID AS 부서코드
FROM EMPLOYEES 
WHERE COMMISSION_PCT IS NULL AND MANAGER_ID IS NOT NULL AND JOB_ID = 'IT_PROG' AND LAST_NAME NOT LIKE 'S%';
